#############################################################################
# Makefile for building: testsqlite
# Generated by qmake (3.0) (Qt 5.6.2)
# Project:  testsqlite.pro
# Template: app
# Command: /home/ctools/qt-5.6-arm/bin/qmake -o Makefile testsqlite.pro
#############################################################################

MAKEFILE      = Makefile

####### Compiler, tools and options

CC            = arm-none-linux-gnueabi-gcc -lts
CXX           = arm-none-linux-gnueabi-g++ -lts
DEFINES       = -DQT_NO_DEBUG -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_SQL_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -O2 -march=armv7-a -O2 -Wall -W -D_REENTRANT -fPIC $(DEFINES)
CXXFLAGS      = -pipe -O2 -march=armv7-a -O2 -march=armv7-a -O2 -std=gnu++0x -Wall -W -D_REENTRANT -fPIC $(DEFINES)
INCPATH       = -I. -I. -I/home/ctools/qt-5.6-arm/include -I/home/ctools/qt-5.6-arm/include/QtWidgets -I/home/ctools/qt-5.6-arm/include/QtGui -I/home/ctools/qt-5.6-arm/include/QtSql -I/home/ctools/qt-5.6-arm/include/QtCore -I. -I. -I/home/vmuser/nfs_shared/tslib/include -I/home/ctools/qt-5.6-arm/mkspecs/linux-arm-gnueabi-g++
QMAKE         = /home/ctools/qt-5.6-arm/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = testsqlite1.0.0
DISTDIR = /mnt/hgfs/winshare/QtProjects/testsqlite/.tmp/testsqlite1.0.0
LINK          = arm-none-linux-gnueabi-g++ -lts
LFLAGS        = -Wl,-O1 -Wl,-rpath,/home/ctools/qt-5.6-arm/lib
LIBS          = $(SUBLIBS) -L/home/vmuser/nfs_shared/tslib/lib -L/home/ctools/qt-5.6-arm/lib -lQt5Widgets -lQt5Gui -lQt5Sql -lQt5Core -lpthread 
AR            = arm-none-linux-gnueabi-ar cqs
RANLIB        = 
SED           = sed
STRIP         = arm-none-linux-gnueabi-strip

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		testsqlite.cpp moc_testsqlite.cpp
OBJECTS       = main.o \
		testsqlite.o \
		moc_testsqlite.o
DIST          = /home/ctools/qt-5.6-arm/mkspecs/features/spec_pre.prf \
		/home/ctools/qt-5.6-arm/mkspecs/common/unix.conf \
		/home/ctools/qt-5.6-arm/mkspecs/common/linux.conf \
		/home/ctools/qt-5.6-arm/mkspecs/common/sanitize.conf \
		/home/ctools/qt-5.6-arm/mkspecs/common/gcc-base.conf \
		/home/ctools/qt-5.6-arm/mkspecs/common/gcc-base-unix.conf \
		/home/ctools/qt-5.6-arm/mkspecs/common/g++-base.conf \
		/home/ctools/qt-5.6-arm/mkspecs/common/g++-unix.conf \
		/home/ctools/qt-5.6-arm/mkspecs/qconfig.pri \
		/home/ctools/qt-5.6-arm/mkspecs/modules/qt_lib_bluetooth.pri \
		/home/ctools/qt-5.6-arm/mkspecs/modules/qt_lib_bluetooth_private.pri \
		/home/ctools/qt-5.6-arm/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/home/ctools/qt-5.6-arm/mkspecs/modules/qt_lib_clucene_private.pri \
		/home/ctools/qt-5.6-arm/mkspecs/modules/qt_lib_concurrent.pri \
		/home/ctools/qt-5.6-arm/mkspecs/modules/qt_lib_concurrent_private.pri \
		/home/ctools/qt-5.6-arm/mkspecs/modules/qt_lib_core.pri \
		/home/ctools/qt-5.6-arm/mkspecs/modules/qt_lib_core_private.pri \
		/home/ctools/qt-5.6-arm/mkspecs/modules/qt_lib_gui.pri \
		/home/ctools/qt-5.6-arm/mkspecs/modules/qt_lib_gui_private.pri \
		/home/ctools/qt-5.6-arm/mkspecs/modules/qt_lib_help.pri \
		/home/ctools/qt-5.6-arm/mkspecs/modules/qt_lib_help_private.pri \
		/home/ctools/qt-5.6-arm/mkspecs/modules/qt_lib_multimedia.pri \
		/home/ctools/qt-5.6-arm/mkspecs/modules/qt_lib_multimedia_private.pri \
		/home/ctools/qt-5.6-arm/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/home/ctools/qt-5.6-arm/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		/home/ctools/qt-5.6-arm/mkspecs/modules/qt_lib_network.pri \
		/home/ctools/qt-5.6-arm/mkspecs/modules/qt_lib_network_private.pri \
		/home/ctools/qt-5.6-arm/mkspecs/modules/qt_lib_nfc.pri \
		/home/ctools/qt-5.6-arm/mkspecs/modules/qt_lib_nfc_private.pri \
		/home/ctools/qt-5.6-arm/mkspecs/modules/qt_lib_platformsupport_private.pri \
		/home/ctools/qt-5.6-arm/mkspecs/modules/qt_lib_positioning.pri \
		/home/ctools/qt-5.6-arm/mkspecs/modules/qt_lib_positioning_private.pri \
		/home/ctools/qt-5.6-arm/mkspecs/modules/qt_lib_printsupport.pri \
		/home/ctools/qt-5.6-arm/mkspecs/modules/qt_lib_printsupport_private.pri \
		/home/ctools/qt-5.6-arm/mkspecs/modules/qt_lib_qml.pri \
		/home/ctools/qt-5.6-arm/mkspecs/modules/qt_lib_qml_private.pri \
		/home/ctools/qt-5.6-arm/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		/home/ctools/qt-5.6-arm/mkspecs/modules/qt_lib_script.pri \
		/home/ctools/qt-5.6-arm/mkspecs/modules/qt_lib_script_private.pri \
		/home/ctools/qt-5.6-arm/mkspecs/modules/qt_lib_scripttools.pri \
		/home/ctools/qt-5.6-arm/mkspecs/modules/qt_lib_scripttools_private.pri \
		/home/ctools/qt-5.6-arm/mkspecs/modules/qt_lib_sensors.pri \
		/home/ctools/qt-5.6-arm/mkspecs/modules/qt_lib_sensors_private.pri \
		/home/ctools/qt-5.6-arm/mkspecs/modules/qt_lib_serialbus.pri \
		/home/ctools/qt-5.6-arm/mkspecs/modules/qt_lib_serialbus_private.pri \
		/home/ctools/qt-5.6-arm/mkspecs/modules/qt_lib_serialport.pri \
		/home/ctools/qt-5.6-arm/mkspecs/modules/qt_lib_serialport_private.pri \
		/home/ctools/qt-5.6-arm/mkspecs/modules/qt_lib_sql.pri \
		/home/ctools/qt-5.6-arm/mkspecs/modules/qt_lib_sql_private.pri \
		/home/ctools/qt-5.6-arm/mkspecs/modules/qt_lib_svg.pri \
		/home/ctools/qt-5.6-arm/mkspecs/modules/qt_lib_svg_private.pri \
		/home/ctools/qt-5.6-arm/mkspecs/modules/qt_lib_testlib.pri \
		/home/ctools/qt-5.6-arm/mkspecs/modules/qt_lib_testlib_private.pri \
		/home/ctools/qt-5.6-arm/mkspecs/modules/qt_lib_uiplugin.pri \
		/home/ctools/qt-5.6-arm/mkspecs/modules/qt_lib_uitools.pri \
		/home/ctools/qt-5.6-arm/mkspecs/modules/qt_lib_uitools_private.pri \
		/home/ctools/qt-5.6-arm/mkspecs/modules/qt_lib_webchannel.pri \
		/home/ctools/qt-5.6-arm/mkspecs/modules/qt_lib_webchannel_private.pri \
		/home/ctools/qt-5.6-arm/mkspecs/modules/qt_lib_websockets.pri \
		/home/ctools/qt-5.6-arm/mkspecs/modules/qt_lib_websockets_private.pri \
		/home/ctools/qt-5.6-arm/mkspecs/modules/qt_lib_widgets.pri \
		/home/ctools/qt-5.6-arm/mkspecs/modules/qt_lib_widgets_private.pri \
		/home/ctools/qt-5.6-arm/mkspecs/modules/qt_lib_xml.pri \
		/home/ctools/qt-5.6-arm/mkspecs/modules/qt_lib_xml_private.pri \
		/home/ctools/qt-5.6-arm/mkspecs/modules/qt_lib_xmlpatterns.pri \
		/home/ctools/qt-5.6-arm/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		/home/ctools/qt-5.6-arm/mkspecs/modules/qt_lib_zlib_private.pri \
		/home/ctools/qt-5.6-arm/mkspecs/features/qt_functions.prf \
		/home/ctools/qt-5.6-arm/mkspecs/features/qt_config.prf \
		/home/ctools/qt-5.6-arm/mkspecs/linux-arm-gnueabi-g++/qmake.conf \
		/home/ctools/qt-5.6-arm/mkspecs/features/spec_post.prf \
		/home/ctools/qt-5.6-arm/mkspecs/features/exclusive_builds.prf \
		/home/ctools/qt-5.6-arm/mkspecs/features/default_pre.prf \
		/home/ctools/qt-5.6-arm/mkspecs/features/resolve_config.prf \
		/home/ctools/qt-5.6-arm/mkspecs/features/default_post.prf \
		/home/ctools/qt-5.6-arm/mkspecs/features/warn_on.prf \
		/home/ctools/qt-5.6-arm/mkspecs/features/qt.prf \
		/home/ctools/qt-5.6-arm/mkspecs/features/resources.prf \
		/home/ctools/qt-5.6-arm/mkspecs/features/moc.prf \
		/home/ctools/qt-5.6-arm/mkspecs/features/uic.prf \
		/home/ctools/qt-5.6-arm/mkspecs/features/unix/thread.prf \
		/home/ctools/qt-5.6-arm/mkspecs/features/file_copies.prf \
		/home/ctools/qt-5.6-arm/mkspecs/features/testcase_targets.prf \
		/home/ctools/qt-5.6-arm/mkspecs/features/exceptions.prf \
		/home/ctools/qt-5.6-arm/mkspecs/features/yacc.prf \
		/home/ctools/qt-5.6-arm/mkspecs/features/lex.prf \
		testsqlite.pro testsqlite.h main.cpp \
		testsqlite.cpp
QMAKE_TARGET  = testsqlite
DESTDIR       = 
TARGET        = testsqlite


first: all
####### Build rules

$(TARGET): ui_testsqlite.h $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: testsqlite.pro /home/ctools/qt-5.6-arm/mkspecs/linux-arm-gnueabi-g++/qmake.conf /home/ctools/qt-5.6-arm/mkspecs/features/spec_pre.prf \
		/home/ctools/qt-5.6-arm/mkspecs/common/unix.conf \
		/home/ctools/qt-5.6-arm/mkspecs/common/linux.conf \
		/home/ctools/qt-5.6-arm/mkspecs/common/sanitize.conf \
		/home/ctools/qt-5.6-arm/mkspecs/common/gcc-base.conf \
		/home/ctools/qt-5.6-arm/mkspecs/common/gcc-base-unix.conf \
		/home/ctools/qt-5.6-arm/mkspecs/common/g++-base.conf \
		/home/ctools/qt-5.6-arm/mkspecs/common/g++-unix.conf \
		/home/ctools/qt-5.6-arm/mkspecs/qconfig.pri \
		/home/ctools/qt-5.6-arm/mkspecs/modules/qt_lib_bluetooth.pri \
		/home/ctools/qt-5.6-arm/mkspecs/modules/qt_lib_bluetooth_private.pri \
		/home/ctools/qt-5.6-arm/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/home/ctools/qt-5.6-arm/mkspecs/modules/qt_lib_clucene_private.pri \
		/home/ctools/qt-5.6-arm/mkspecs/modules/qt_lib_concurrent.pri \
		/home/ctools/qt-5.6-arm/mkspecs/modules/qt_lib_concurrent_private.pri \
		/home/ctools/qt-5.6-arm/mkspecs/modules/qt_lib_core.pri \
		/home/ctools/qt-5.6-arm/mkspecs/modules/qt_lib_core_private.pri \
		/home/ctools/qt-5.6-arm/mkspecs/modules/qt_lib_gui.pri \
		/home/ctools/qt-5.6-arm/mkspecs/modules/qt_lib_gui_private.pri \
		/home/ctools/qt-5.6-arm/mkspecs/modules/qt_lib_help.pri \
		/home/ctools/qt-5.6-arm/mkspecs/modules/qt_lib_help_private.pri \
		/home/ctools/qt-5.6-arm/mkspecs/modules/qt_lib_multimedia.pri \
		/home/ctools/qt-5.6-arm/mkspecs/modules/qt_lib_multimedia_private.pri \
		/home/ctools/qt-5.6-arm/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/home/ctools/qt-5.6-arm/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		/home/ctools/qt-5.6-arm/mkspecs/modules/qt_lib_network.pri \
		/home/ctools/qt-5.6-arm/mkspecs/modules/qt_lib_network_private.pri \
		/home/ctools/qt-5.6-arm/mkspecs/modules/qt_lib_nfc.pri \
		/home/ctools/qt-5.6-arm/mkspecs/modules/qt_lib_nfc_private.pri \
		/home/ctools/qt-5.6-arm/mkspecs/modules/qt_lib_platformsupport_private.pri \
		/home/ctools/qt-5.6-arm/mkspecs/modules/qt_lib_positioning.pri \
		/home/ctools/qt-5.6-arm/mkspecs/modules/qt_lib_positioning_private.pri \
		/home/ctools/qt-5.6-arm/mkspecs/modules/qt_lib_printsupport.pri \
		/home/ctools/qt-5.6-arm/mkspecs/modules/qt_lib_printsupport_private.pri \
		/home/ctools/qt-5.6-arm/mkspecs/modules/qt_lib_qml.pri \
		/home/ctools/qt-5.6-arm/mkspecs/modules/qt_lib_qml_private.pri \
		/home/ctools/qt-5.6-arm/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		/home/ctools/qt-5.6-arm/mkspecs/modules/qt_lib_script.pri \
		/home/ctools/qt-5.6-arm/mkspecs/modules/qt_lib_script_private.pri \
		/home/ctools/qt-5.6-arm/mkspecs/modules/qt_lib_scripttools.pri \
		/home/ctools/qt-5.6-arm/mkspecs/modules/qt_lib_scripttools_private.pri \
		/home/ctools/qt-5.6-arm/mkspecs/modules/qt_lib_sensors.pri \
		/home/ctools/qt-5.6-arm/mkspecs/modules/qt_lib_sensors_private.pri \
		/home/ctools/qt-5.6-arm/mkspecs/modules/qt_lib_serialbus.pri \
		/home/ctools/qt-5.6-arm/mkspecs/modules/qt_lib_serialbus_private.pri \
		/home/ctools/qt-5.6-arm/mkspecs/modules/qt_lib_serialport.pri \
		/home/ctools/qt-5.6-arm/mkspecs/modules/qt_lib_serialport_private.pri \
		/home/ctools/qt-5.6-arm/mkspecs/modules/qt_lib_sql.pri \
		/home/ctools/qt-5.6-arm/mkspecs/modules/qt_lib_sql_private.pri \
		/home/ctools/qt-5.6-arm/mkspecs/modules/qt_lib_svg.pri \
		/home/ctools/qt-5.6-arm/mkspecs/modules/qt_lib_svg_private.pri \
		/home/ctools/qt-5.6-arm/mkspecs/modules/qt_lib_testlib.pri \
		/home/ctools/qt-5.6-arm/mkspecs/modules/qt_lib_testlib_private.pri \
		/home/ctools/qt-5.6-arm/mkspecs/modules/qt_lib_uiplugin.pri \
		/home/ctools/qt-5.6-arm/mkspecs/modules/qt_lib_uitools.pri \
		/home/ctools/qt-5.6-arm/mkspecs/modules/qt_lib_uitools_private.pri \
		/home/ctools/qt-5.6-arm/mkspecs/modules/qt_lib_webchannel.pri \
		/home/ctools/qt-5.6-arm/mkspecs/modules/qt_lib_webchannel_private.pri \
		/home/ctools/qt-5.6-arm/mkspecs/modules/qt_lib_websockets.pri \
		/home/ctools/qt-5.6-arm/mkspecs/modules/qt_lib_websockets_private.pri \
		/home/ctools/qt-5.6-arm/mkspecs/modules/qt_lib_widgets.pri \
		/home/ctools/qt-5.6-arm/mkspecs/modules/qt_lib_widgets_private.pri \
		/home/ctools/qt-5.6-arm/mkspecs/modules/qt_lib_xml.pri \
		/home/ctools/qt-5.6-arm/mkspecs/modules/qt_lib_xml_private.pri \
		/home/ctools/qt-5.6-arm/mkspecs/modules/qt_lib_xmlpatterns.pri \
		/home/ctools/qt-5.6-arm/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		/home/ctools/qt-5.6-arm/mkspecs/modules/qt_lib_zlib_private.pri \
		/home/ctools/qt-5.6-arm/mkspecs/features/qt_functions.prf \
		/home/ctools/qt-5.6-arm/mkspecs/features/qt_config.prf \
		/home/ctools/qt-5.6-arm/mkspecs/linux-arm-gnueabi-g++/qmake.conf \
		/home/ctools/qt-5.6-arm/mkspecs/features/spec_post.prf \
		/home/ctools/qt-5.6-arm/mkspecs/features/exclusive_builds.prf \
		/home/ctools/qt-5.6-arm/mkspecs/features/default_pre.prf \
		/home/ctools/qt-5.6-arm/mkspecs/features/resolve_config.prf \
		/home/ctools/qt-5.6-arm/mkspecs/features/default_post.prf \
		/home/ctools/qt-5.6-arm/mkspecs/features/warn_on.prf \
		/home/ctools/qt-5.6-arm/mkspecs/features/qt.prf \
		/home/ctools/qt-5.6-arm/mkspecs/features/resources.prf \
		/home/ctools/qt-5.6-arm/mkspecs/features/moc.prf \
		/home/ctools/qt-5.6-arm/mkspecs/features/uic.prf \
		/home/ctools/qt-5.6-arm/mkspecs/features/unix/thread.prf \
		/home/ctools/qt-5.6-arm/mkspecs/features/file_copies.prf \
		/home/ctools/qt-5.6-arm/mkspecs/features/testcase_targets.prf \
		/home/ctools/qt-5.6-arm/mkspecs/features/exceptions.prf \
		/home/ctools/qt-5.6-arm/mkspecs/features/yacc.prf \
		/home/ctools/qt-5.6-arm/mkspecs/features/lex.prf \
		testsqlite.pro \
		/home/ctools/qt-5.6-arm/lib/libQt5Widgets.prl \
		/home/ctools/qt-5.6-arm/lib/libQt5Gui.prl \
		/home/ctools/qt-5.6-arm/lib/libQt5Sql.prl \
		/home/ctools/qt-5.6-arm/lib/libQt5Core.prl
	$(QMAKE) -o Makefile testsqlite.pro
/home/ctools/qt-5.6-arm/mkspecs/features/spec_pre.prf:
/home/ctools/qt-5.6-arm/mkspecs/common/unix.conf:
/home/ctools/qt-5.6-arm/mkspecs/common/linux.conf:
/home/ctools/qt-5.6-arm/mkspecs/common/sanitize.conf:
/home/ctools/qt-5.6-arm/mkspecs/common/gcc-base.conf:
/home/ctools/qt-5.6-arm/mkspecs/common/gcc-base-unix.conf:
/home/ctools/qt-5.6-arm/mkspecs/common/g++-base.conf:
/home/ctools/qt-5.6-arm/mkspecs/common/g++-unix.conf:
/home/ctools/qt-5.6-arm/mkspecs/qconfig.pri:
/home/ctools/qt-5.6-arm/mkspecs/modules/qt_lib_bluetooth.pri:
/home/ctools/qt-5.6-arm/mkspecs/modules/qt_lib_bluetooth_private.pri:
/home/ctools/qt-5.6-arm/mkspecs/modules/qt_lib_bootstrap_private.pri:
/home/ctools/qt-5.6-arm/mkspecs/modules/qt_lib_clucene_private.pri:
/home/ctools/qt-5.6-arm/mkspecs/modules/qt_lib_concurrent.pri:
/home/ctools/qt-5.6-arm/mkspecs/modules/qt_lib_concurrent_private.pri:
/home/ctools/qt-5.6-arm/mkspecs/modules/qt_lib_core.pri:
/home/ctools/qt-5.6-arm/mkspecs/modules/qt_lib_core_private.pri:
/home/ctools/qt-5.6-arm/mkspecs/modules/qt_lib_gui.pri:
/home/ctools/qt-5.6-arm/mkspecs/modules/qt_lib_gui_private.pri:
/home/ctools/qt-5.6-arm/mkspecs/modules/qt_lib_help.pri:
/home/ctools/qt-5.6-arm/mkspecs/modules/qt_lib_help_private.pri:
/home/ctools/qt-5.6-arm/mkspecs/modules/qt_lib_multimedia.pri:
/home/ctools/qt-5.6-arm/mkspecs/modules/qt_lib_multimedia_private.pri:
/home/ctools/qt-5.6-arm/mkspecs/modules/qt_lib_multimediawidgets.pri:
/home/ctools/qt-5.6-arm/mkspecs/modules/qt_lib_multimediawidgets_private.pri:
/home/ctools/qt-5.6-arm/mkspecs/modules/qt_lib_network.pri:
/home/ctools/qt-5.6-arm/mkspecs/modules/qt_lib_network_private.pri:
/home/ctools/qt-5.6-arm/mkspecs/modules/qt_lib_nfc.pri:
/home/ctools/qt-5.6-arm/mkspecs/modules/qt_lib_nfc_private.pri:
/home/ctools/qt-5.6-arm/mkspecs/modules/qt_lib_platformsupport_private.pri:
/home/ctools/qt-5.6-arm/mkspecs/modules/qt_lib_positioning.pri:
/home/ctools/qt-5.6-arm/mkspecs/modules/qt_lib_positioning_private.pri:
/home/ctools/qt-5.6-arm/mkspecs/modules/qt_lib_printsupport.pri:
/home/ctools/qt-5.6-arm/mkspecs/modules/qt_lib_printsupport_private.pri:
/home/ctools/qt-5.6-arm/mkspecs/modules/qt_lib_qml.pri:
/home/ctools/qt-5.6-arm/mkspecs/modules/qt_lib_qml_private.pri:
/home/ctools/qt-5.6-arm/mkspecs/modules/qt_lib_qmldevtools_private.pri:
/home/ctools/qt-5.6-arm/mkspecs/modules/qt_lib_script.pri:
/home/ctools/qt-5.6-arm/mkspecs/modules/qt_lib_script_private.pri:
/home/ctools/qt-5.6-arm/mkspecs/modules/qt_lib_scripttools.pri:
/home/ctools/qt-5.6-arm/mkspecs/modules/qt_lib_scripttools_private.pri:
/home/ctools/qt-5.6-arm/mkspecs/modules/qt_lib_sensors.pri:
/home/ctools/qt-5.6-arm/mkspecs/modules/qt_lib_sensors_private.pri:
/home/ctools/qt-5.6-arm/mkspecs/modules/qt_lib_serialbus.pri:
/home/ctools/qt-5.6-arm/mkspecs/modules/qt_lib_serialbus_private.pri:
/home/ctools/qt-5.6-arm/mkspecs/modules/qt_lib_serialport.pri:
/home/ctools/qt-5.6-arm/mkspecs/modules/qt_lib_serialport_private.pri:
/home/ctools/qt-5.6-arm/mkspecs/modules/qt_lib_sql.pri:
/home/ctools/qt-5.6-arm/mkspecs/modules/qt_lib_sql_private.pri:
/home/ctools/qt-5.6-arm/mkspecs/modules/qt_lib_svg.pri:
/home/ctools/qt-5.6-arm/mkspecs/modules/qt_lib_svg_private.pri:
/home/ctools/qt-5.6-arm/mkspecs/modules/qt_lib_testlib.pri:
/home/ctools/qt-5.6-arm/mkspecs/modules/qt_lib_testlib_private.pri:
/home/ctools/qt-5.6-arm/mkspecs/modules/qt_lib_uiplugin.pri:
/home/ctools/qt-5.6-arm/mkspecs/modules/qt_lib_uitools.pri:
/home/ctools/qt-5.6-arm/mkspecs/modules/qt_lib_uitools_private.pri:
/home/ctools/qt-5.6-arm/mkspecs/modules/qt_lib_webchannel.pri:
/home/ctools/qt-5.6-arm/mkspecs/modules/qt_lib_webchannel_private.pri:
/home/ctools/qt-5.6-arm/mkspecs/modules/qt_lib_websockets.pri:
/home/ctools/qt-5.6-arm/mkspecs/modules/qt_lib_websockets_private.pri:
/home/ctools/qt-5.6-arm/mkspecs/modules/qt_lib_widgets.pri:
/home/ctools/qt-5.6-arm/mkspecs/modules/qt_lib_widgets_private.pri:
/home/ctools/qt-5.6-arm/mkspecs/modules/qt_lib_xml.pri:
/home/ctools/qt-5.6-arm/mkspecs/modules/qt_lib_xml_private.pri:
/home/ctools/qt-5.6-arm/mkspecs/modules/qt_lib_xmlpatterns.pri:
/home/ctools/qt-5.6-arm/mkspecs/modules/qt_lib_xmlpatterns_private.pri:
/home/ctools/qt-5.6-arm/mkspecs/modules/qt_lib_zlib_private.pri:
/home/ctools/qt-5.6-arm/mkspecs/features/qt_functions.prf:
/home/ctools/qt-5.6-arm/mkspecs/features/qt_config.prf:
/home/ctools/qt-5.6-arm/mkspecs/linux-arm-gnueabi-g++/qmake.conf:
/home/ctools/qt-5.6-arm/mkspecs/features/spec_post.prf:
/home/ctools/qt-5.6-arm/mkspecs/features/exclusive_builds.prf:
/home/ctools/qt-5.6-arm/mkspecs/features/default_pre.prf:
/home/ctools/qt-5.6-arm/mkspecs/features/resolve_config.prf:
/home/ctools/qt-5.6-arm/mkspecs/features/default_post.prf:
/home/ctools/qt-5.6-arm/mkspecs/features/warn_on.prf:
/home/ctools/qt-5.6-arm/mkspecs/features/qt.prf:
/home/ctools/qt-5.6-arm/mkspecs/features/resources.prf:
/home/ctools/qt-5.6-arm/mkspecs/features/moc.prf:
/home/ctools/qt-5.6-arm/mkspecs/features/uic.prf:
/home/ctools/qt-5.6-arm/mkspecs/features/unix/thread.prf:
/home/ctools/qt-5.6-arm/mkspecs/features/file_copies.prf:
/home/ctools/qt-5.6-arm/mkspecs/features/testcase_targets.prf:
/home/ctools/qt-5.6-arm/mkspecs/features/exceptions.prf:
/home/ctools/qt-5.6-arm/mkspecs/features/yacc.prf:
/home/ctools/qt-5.6-arm/mkspecs/features/lex.prf:
testsqlite.pro:
/home/ctools/qt-5.6-arm/lib/libQt5Widgets.prl:
/home/ctools/qt-5.6-arm/lib/libQt5Gui.prl:
/home/ctools/qt-5.6-arm/lib/libQt5Sql.prl:
/home/ctools/qt-5.6-arm/lib/libQt5Core.prl:
qmake: FORCE
	@$(QMAKE) -o Makefile testsqlite.pro

qmake_all: FORCE


all: Makefile $(TARGET)

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents testsqlite.h $(DISTDIR)/
	$(COPY_FILE) --parents main.cpp testsqlite.cpp $(DISTDIR)/
	$(COPY_FILE) --parents testsqlite.ui $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


####### Sub-libraries

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

check: first

benchmark: first

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_moc_header_make_all: moc_testsqlite.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_testsqlite.cpp
moc_testsqlite.cpp: /home/ctools/qt-5.6-arm/include/QtWidgets/QMainWindow \
		/home/ctools/qt-5.6-arm/include/QtWidgets/qmainwindow.h \
		/home/ctools/qt-5.6-arm/include/QtWidgets/qwidget.h \
		/home/ctools/qt-5.6-arm/include/QtGui/qwindowdefs.h \
		/home/ctools/qt-5.6-arm/include/QtCore/qglobal.h \
		/home/ctools/qt-5.6-arm/include/QtCore/qconfig.h \
		/home/ctools/qt-5.6-arm/include/QtCore/qfeatures.h \
		/home/ctools/qt-5.6-arm/include/QtCore/qsystemdetection.h \
		/home/ctools/qt-5.6-arm/include/QtCore/qprocessordetection.h \
		/home/ctools/qt-5.6-arm/include/QtCore/qcompilerdetection.h \
		/home/ctools/qt-5.6-arm/include/QtCore/qtypeinfo.h \
		/home/ctools/qt-5.6-arm/include/QtCore/qtypetraits.h \
		/home/ctools/qt-5.6-arm/include/QtCore/qisenum.h \
		/home/ctools/qt-5.6-arm/include/QtCore/qsysinfo.h \
		/home/ctools/qt-5.6-arm/include/QtCore/qlogging.h \
		/home/ctools/qt-5.6-arm/include/QtCore/qflags.h \
		/home/ctools/qt-5.6-arm/include/QtCore/qatomic.h \
		/home/ctools/qt-5.6-arm/include/QtCore/qbasicatomic.h \
		/home/ctools/qt-5.6-arm/include/QtCore/qatomic_bootstrap.h \
		/home/ctools/qt-5.6-arm/include/QtCore/qgenericatomic.h \
		/home/ctools/qt-5.6-arm/include/QtCore/qatomic_cxx11.h \
		/home/ctools/qt-5.6-arm/include/QtCore/qatomic_gcc.h \
		/home/ctools/qt-5.6-arm/include/QtCore/qatomic_msvc.h \
		/home/ctools/qt-5.6-arm/include/QtCore/qatomic_armv7.h \
		/home/ctools/qt-5.6-arm/include/QtCore/qatomic_armv6.h \
		/home/ctools/qt-5.6-arm/include/QtCore/qatomic_armv5.h \
		/home/ctools/qt-5.6-arm/include/QtCore/qatomic_ia64.h \
		/home/ctools/qt-5.6-arm/include/QtCore/qatomic_x86.h \
		/home/ctools/qt-5.6-arm/include/QtCore/qatomic_unix.h \
		/home/ctools/qt-5.6-arm/include/QtCore/qglobalstatic.h \
		/home/ctools/qt-5.6-arm/include/QtCore/qmutex.h \
		/home/ctools/qt-5.6-arm/include/QtCore/qnumeric.h \
		/home/ctools/qt-5.6-arm/include/QtCore/qversiontagging.h \
		/home/ctools/qt-5.6-arm/include/QtCore/qobjectdefs.h \
		/home/ctools/qt-5.6-arm/include/QtCore/qnamespace.h \
		/home/ctools/qt-5.6-arm/include/QtCore/qobjectdefs_impl.h \
		/home/ctools/qt-5.6-arm/include/QtGui/qwindowdefs_win.h \
		/home/ctools/qt-5.6-arm/include/QtCore/qobject.h \
		/home/ctools/qt-5.6-arm/include/QtCore/qstring.h \
		/home/ctools/qt-5.6-arm/include/QtCore/qchar.h \
		/home/ctools/qt-5.6-arm/include/QtCore/qbytearray.h \
		/home/ctools/qt-5.6-arm/include/QtCore/qrefcount.h \
		/home/ctools/qt-5.6-arm/include/QtCore/qarraydata.h \
		/home/ctools/qt-5.6-arm/include/QtCore/qstringbuilder.h \
		/home/ctools/qt-5.6-arm/include/QtCore/qlist.h \
		/home/ctools/qt-5.6-arm/include/QtCore/qalgorithms.h \
		/home/ctools/qt-5.6-arm/include/QtCore/qiterator.h \
		/home/ctools/qt-5.6-arm/include/QtCore/qhashfunctions.h \
		/home/ctools/qt-5.6-arm/include/QtCore/qpair.h \
		/home/ctools/qt-5.6-arm/include/QtCore/qbytearraylist.h \
		/home/ctools/qt-5.6-arm/include/QtCore/qstringlist.h \
		/home/ctools/qt-5.6-arm/include/QtCore/qregexp.h \
		/home/ctools/qt-5.6-arm/include/QtCore/qstringmatcher.h \
		/home/ctools/qt-5.6-arm/include/QtCore/qcoreevent.h \
		/home/ctools/qt-5.6-arm/include/QtCore/qscopedpointer.h \
		/home/ctools/qt-5.6-arm/include/QtCore/qmetatype.h \
		/home/ctools/qt-5.6-arm/include/QtCore/qvarlengtharray.h \
		/home/ctools/qt-5.6-arm/include/QtCore/qcontainerfwd.h \
		/home/ctools/qt-5.6-arm/include/QtCore/qobject_impl.h \
		/home/ctools/qt-5.6-arm/include/QtCore/qmargins.h \
		/home/ctools/qt-5.6-arm/include/QtGui/qpaintdevice.h \
		/home/ctools/qt-5.6-arm/include/QtCore/qrect.h \
		/home/ctools/qt-5.6-arm/include/QtCore/qsize.h \
		/home/ctools/qt-5.6-arm/include/QtCore/qpoint.h \
		/home/ctools/qt-5.6-arm/include/QtGui/qpalette.h \
		/home/ctools/qt-5.6-arm/include/QtGui/qcolor.h \
		/home/ctools/qt-5.6-arm/include/QtGui/qrgb.h \
		/home/ctools/qt-5.6-arm/include/QtGui/qrgba64.h \
		/home/ctools/qt-5.6-arm/include/QtGui/qbrush.h \
		/home/ctools/qt-5.6-arm/include/QtCore/qvector.h \
		/home/ctools/qt-5.6-arm/include/QtGui/qmatrix.h \
		/home/ctools/qt-5.6-arm/include/QtGui/qpolygon.h \
		/home/ctools/qt-5.6-arm/include/QtGui/qregion.h \
		/home/ctools/qt-5.6-arm/include/QtCore/qdatastream.h \
		/home/ctools/qt-5.6-arm/include/QtCore/qiodevice.h \
		/home/ctools/qt-5.6-arm/include/QtCore/qline.h \
		/home/ctools/qt-5.6-arm/include/QtGui/qtransform.h \
		/home/ctools/qt-5.6-arm/include/QtGui/qpainterpath.h \
		/home/ctools/qt-5.6-arm/include/QtGui/qimage.h \
		/home/ctools/qt-5.6-arm/include/QtGui/qpixelformat.h \
		/home/ctools/qt-5.6-arm/include/QtGui/qpixmap.h \
		/home/ctools/qt-5.6-arm/include/QtCore/qsharedpointer.h \
		/home/ctools/qt-5.6-arm/include/QtCore/qshareddata.h \
		/home/ctools/qt-5.6-arm/include/QtCore/qhash.h \
		/home/ctools/qt-5.6-arm/include/QtCore/qsharedpointer_impl.h \
		/home/ctools/qt-5.6-arm/include/QtGui/qfont.h \
		/home/ctools/qt-5.6-arm/include/QtGui/qfontmetrics.h \
		/home/ctools/qt-5.6-arm/include/QtGui/qfontinfo.h \
		/home/ctools/qt-5.6-arm/include/QtWidgets/qsizepolicy.h \
		/home/ctools/qt-5.6-arm/include/QtGui/qcursor.h \
		/home/ctools/qt-5.6-arm/include/QtGui/qkeysequence.h \
		/home/ctools/qt-5.6-arm/include/QtGui/qevent.h \
		/home/ctools/qt-5.6-arm/include/QtCore/qvariant.h \
		/home/ctools/qt-5.6-arm/include/QtCore/qmap.h \
		/home/ctools/qt-5.6-arm/include/QtCore/qdebug.h \
		/home/ctools/qt-5.6-arm/include/QtCore/qtextstream.h \
		/home/ctools/qt-5.6-arm/include/QtCore/qlocale.h \
		/home/ctools/qt-5.6-arm/include/QtCore/qset.h \
		/home/ctools/qt-5.6-arm/include/QtCore/qcontiguouscache.h \
		/home/ctools/qt-5.6-arm/include/QtCore/qurl.h \
		/home/ctools/qt-5.6-arm/include/QtCore/qurlquery.h \
		/home/ctools/qt-5.6-arm/include/QtCore/qfile.h \
		/home/ctools/qt-5.6-arm/include/QtCore/qfiledevice.h \
		/home/ctools/qt-5.6-arm/include/QtGui/qvector2d.h \
		/home/ctools/qt-5.6-arm/include/QtGui/qtouchdevice.h \
		/home/ctools/qt-5.6-arm/include/QtWidgets/qtabwidget.h \
		/home/ctools/qt-5.6-arm/include/QtGui/qicon.h \
		testsqlite.h
	/home/ctools/qt-5.6-arm/bin/moc $(DEFINES) -I/home/ctools/qt-5.6-arm/mkspecs/linux-arm-gnueabi-g++ -I/mnt/hgfs/winshare/QtProjects/testsqlite -I/mnt/hgfs/winshare/QtProjects/testsqlite -I/home/ctools/qt-5.6-arm/include -I/home/ctools/qt-5.6-arm/include/QtWidgets -I/home/ctools/qt-5.6-arm/include/QtGui -I/home/ctools/qt-5.6-arm/include/QtSql -I/home/ctools/qt-5.6-arm/include/QtCore -I/home/ctools/arm-2014.05/arm-none-linux-gnueabi/include/c++/4.8.3 -I/home/ctools/arm-2014.05/arm-none-linux-gnueabi/include/c++/4.8.3/arm-none-linux-gnueabi -I/home/ctools/arm-2014.05/arm-none-linux-gnueabi/include/c++/4.8.3/backward -I/home/ctools/arm-2014.05/lib/gcc/arm-none-linux-gnueabi/4.8.3/include -I/home/ctools/arm-2014.05/lib/gcc/arm-none-linux-gnueabi/4.8.3/include-fixed -I/home/ctools/arm-2014.05/arm-none-linux-gnueabi/include -I/home/ctools/arm-2014.05/arm-none-linux-gnueabi/libc/usr/include testsqlite.h -o moc_testsqlite.cpp

compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_testsqlite.h
compiler_uic_clean:
	-$(DEL_FILE) ui_testsqlite.h
ui_testsqlite.h: testsqlite.ui
	/home/ctools/qt-5.6-arm/bin/uic testsqlite.ui -o ui_testsqlite.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_uic_clean 

####### Compile

main.o: main.cpp testsqlite.h \
		/home/ctools/qt-5.6-arm/include/QtWidgets/QMainWindow \
		/home/ctools/qt-5.6-arm/include/QtWidgets/qmainwindow.h \
		/home/ctools/qt-5.6-arm/include/QtWidgets/qwidget.h \
		/home/ctools/qt-5.6-arm/include/QtGui/qwindowdefs.h \
		/home/ctools/qt-5.6-arm/include/QtCore/qglobal.h \
		/home/ctools/qt-5.6-arm/include/QtCore/qconfig.h \
		/home/ctools/qt-5.6-arm/include/QtCore/qfeatures.h \
		/home/ctools/qt-5.6-arm/include/QtCore/qsystemdetection.h \
		/home/ctools/qt-5.6-arm/include/QtCore/qprocessordetection.h \
		/home/ctools/qt-5.6-arm/include/QtCore/qcompilerdetection.h \
		/home/ctools/qt-5.6-arm/include/QtCore/qtypeinfo.h \
		/home/ctools/qt-5.6-arm/include/QtCore/qtypetraits.h \
		/home/ctools/qt-5.6-arm/include/QtCore/qisenum.h \
		/home/ctools/qt-5.6-arm/include/QtCore/qsysinfo.h \
		/home/ctools/qt-5.6-arm/include/QtCore/qlogging.h \
		/home/ctools/qt-5.6-arm/include/QtCore/qflags.h \
		/home/ctools/qt-5.6-arm/include/QtCore/qatomic.h \
		/home/ctools/qt-5.6-arm/include/QtCore/qbasicatomic.h \
		/home/ctools/qt-5.6-arm/include/QtCore/qatomic_bootstrap.h \
		/home/ctools/qt-5.6-arm/include/QtCore/qgenericatomic.h \
		/home/ctools/qt-5.6-arm/include/QtCore/qatomic_cxx11.h \
		/home/ctools/qt-5.6-arm/include/QtCore/qatomic_gcc.h \
		/home/ctools/qt-5.6-arm/include/QtCore/qatomic_msvc.h \
		/home/ctools/qt-5.6-arm/include/QtCore/qatomic_armv7.h \
		/home/ctools/qt-5.6-arm/include/QtCore/qatomic_armv6.h \
		/home/ctools/qt-5.6-arm/include/QtCore/qatomic_armv5.h \
		/home/ctools/qt-5.6-arm/include/QtCore/qatomic_ia64.h \
		/home/ctools/qt-5.6-arm/include/QtCore/qatomic_x86.h \
		/home/ctools/qt-5.6-arm/include/QtCore/qatomic_unix.h \
		/home/ctools/qt-5.6-arm/include/QtCore/qglobalstatic.h \
		/home/ctools/qt-5.6-arm/include/QtCore/qmutex.h \
		/home/ctools/qt-5.6-arm/include/QtCore/qnumeric.h \
		/home/ctools/qt-5.6-arm/include/QtCore/qversiontagging.h \
		/home/ctools/qt-5.6-arm/include/QtCore/qobjectdefs.h \
		/home/ctools/qt-5.6-arm/include/QtCore/qnamespace.h \
		/home/ctools/qt-5.6-arm/include/QtCore/qobjectdefs_impl.h \
		/home/ctools/qt-5.6-arm/include/QtGui/qwindowdefs_win.h \
		/home/ctools/qt-5.6-arm/include/QtCore/qobject.h \
		/home/ctools/qt-5.6-arm/include/QtCore/qstring.h \
		/home/ctools/qt-5.6-arm/include/QtCore/qchar.h \
		/home/ctools/qt-5.6-arm/include/QtCore/qbytearray.h \
		/home/ctools/qt-5.6-arm/include/QtCore/qrefcount.h \
		/home/ctools/qt-5.6-arm/include/QtCore/qarraydata.h \
		/home/ctools/qt-5.6-arm/include/QtCore/qstringbuilder.h \
		/home/ctools/qt-5.6-arm/include/QtCore/qlist.h \
		/home/ctools/qt-5.6-arm/include/QtCore/qalgorithms.h \
		/home/ctools/qt-5.6-arm/include/QtCore/qiterator.h \
		/home/ctools/qt-5.6-arm/include/QtCore/qhashfunctions.h \
		/home/ctools/qt-5.6-arm/include/QtCore/qpair.h \
		/home/ctools/qt-5.6-arm/include/QtCore/qbytearraylist.h \
		/home/ctools/qt-5.6-arm/include/QtCore/qstringlist.h \
		/home/ctools/qt-5.6-arm/include/QtCore/qregexp.h \
		/home/ctools/qt-5.6-arm/include/QtCore/qstringmatcher.h \
		/home/ctools/qt-5.6-arm/include/QtCore/qcoreevent.h \
		/home/ctools/qt-5.6-arm/include/QtCore/qscopedpointer.h \
		/home/ctools/qt-5.6-arm/include/QtCore/qmetatype.h \
		/home/ctools/qt-5.6-arm/include/QtCore/qvarlengtharray.h \
		/home/ctools/qt-5.6-arm/include/QtCore/qcontainerfwd.h \
		/home/ctools/qt-5.6-arm/include/QtCore/qobject_impl.h \
		/home/ctools/qt-5.6-arm/include/QtCore/qmargins.h \
		/home/ctools/qt-5.6-arm/include/QtGui/qpaintdevice.h \
		/home/ctools/qt-5.6-arm/include/QtCore/qrect.h \
		/home/ctools/qt-5.6-arm/include/QtCore/qsize.h \
		/home/ctools/qt-5.6-arm/include/QtCore/qpoint.h \
		/home/ctools/qt-5.6-arm/include/QtGui/qpalette.h \
		/home/ctools/qt-5.6-arm/include/QtGui/qcolor.h \
		/home/ctools/qt-5.6-arm/include/QtGui/qrgb.h \
		/home/ctools/qt-5.6-arm/include/QtGui/qrgba64.h \
		/home/ctools/qt-5.6-arm/include/QtGui/qbrush.h \
		/home/ctools/qt-5.6-arm/include/QtCore/qvector.h \
		/home/ctools/qt-5.6-arm/include/QtGui/qmatrix.h \
		/home/ctools/qt-5.6-arm/include/QtGui/qpolygon.h \
		/home/ctools/qt-5.6-arm/include/QtGui/qregion.h \
		/home/ctools/qt-5.6-arm/include/QtCore/qdatastream.h \
		/home/ctools/qt-5.6-arm/include/QtCore/qiodevice.h \
		/home/ctools/qt-5.6-arm/include/QtCore/qline.h \
		/home/ctools/qt-5.6-arm/include/QtGui/qtransform.h \
		/home/ctools/qt-5.6-arm/include/QtGui/qpainterpath.h \
		/home/ctools/qt-5.6-arm/include/QtGui/qimage.h \
		/home/ctools/qt-5.6-arm/include/QtGui/qpixelformat.h \
		/home/ctools/qt-5.6-arm/include/QtGui/qpixmap.h \
		/home/ctools/qt-5.6-arm/include/QtCore/qsharedpointer.h \
		/home/ctools/qt-5.6-arm/include/QtCore/qshareddata.h \
		/home/ctools/qt-5.6-arm/include/QtCore/qhash.h \
		/home/ctools/qt-5.6-arm/include/QtCore/qsharedpointer_impl.h \
		/home/ctools/qt-5.6-arm/include/QtGui/qfont.h \
		/home/ctools/qt-5.6-arm/include/QtGui/qfontmetrics.h \
		/home/ctools/qt-5.6-arm/include/QtGui/qfontinfo.h \
		/home/ctools/qt-5.6-arm/include/QtWidgets/qsizepolicy.h \
		/home/ctools/qt-5.6-arm/include/QtGui/qcursor.h \
		/home/ctools/qt-5.6-arm/include/QtGui/qkeysequence.h \
		/home/ctools/qt-5.6-arm/include/QtGui/qevent.h \
		/home/ctools/qt-5.6-arm/include/QtCore/qvariant.h \
		/home/ctools/qt-5.6-arm/include/QtCore/qmap.h \
		/home/ctools/qt-5.6-arm/include/QtCore/qdebug.h \
		/home/ctools/qt-5.6-arm/include/QtCore/qtextstream.h \
		/home/ctools/qt-5.6-arm/include/QtCore/qlocale.h \
		/home/ctools/qt-5.6-arm/include/QtCore/qset.h \
		/home/ctools/qt-5.6-arm/include/QtCore/qcontiguouscache.h \
		/home/ctools/qt-5.6-arm/include/QtCore/qurl.h \
		/home/ctools/qt-5.6-arm/include/QtCore/qurlquery.h \
		/home/ctools/qt-5.6-arm/include/QtCore/qfile.h \
		/home/ctools/qt-5.6-arm/include/QtCore/qfiledevice.h \
		/home/ctools/qt-5.6-arm/include/QtGui/qvector2d.h \
		/home/ctools/qt-5.6-arm/include/QtGui/qtouchdevice.h \
		/home/ctools/qt-5.6-arm/include/QtWidgets/qtabwidget.h \
		/home/ctools/qt-5.6-arm/include/QtGui/qicon.h \
		/home/ctools/qt-5.6-arm/include/QtWidgets/QApplication \
		/home/ctools/qt-5.6-arm/include/QtWidgets/qapplication.h \
		/home/ctools/qt-5.6-arm/include/QtCore/qcoreapplication.h \
		/home/ctools/qt-5.6-arm/include/QtCore/qeventloop.h \
		/home/ctools/qt-5.6-arm/include/QtWidgets/qdesktopwidget.h \
		/home/ctools/qt-5.6-arm/include/QtGui/qguiapplication.h \
		/home/ctools/qt-5.6-arm/include/QtGui/qinputmethod.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

testsqlite.o: testsqlite.cpp testsqlite.h \
		/home/ctools/qt-5.6-arm/include/QtWidgets/QMainWindow \
		/home/ctools/qt-5.6-arm/include/QtWidgets/qmainwindow.h \
		/home/ctools/qt-5.6-arm/include/QtWidgets/qwidget.h \
		/home/ctools/qt-5.6-arm/include/QtGui/qwindowdefs.h \
		/home/ctools/qt-5.6-arm/include/QtCore/qglobal.h \
		/home/ctools/qt-5.6-arm/include/QtCore/qconfig.h \
		/home/ctools/qt-5.6-arm/include/QtCore/qfeatures.h \
		/home/ctools/qt-5.6-arm/include/QtCore/qsystemdetection.h \
		/home/ctools/qt-5.6-arm/include/QtCore/qprocessordetection.h \
		/home/ctools/qt-5.6-arm/include/QtCore/qcompilerdetection.h \
		/home/ctools/qt-5.6-arm/include/QtCore/qtypeinfo.h \
		/home/ctools/qt-5.6-arm/include/QtCore/qtypetraits.h \
		/home/ctools/qt-5.6-arm/include/QtCore/qisenum.h \
		/home/ctools/qt-5.6-arm/include/QtCore/qsysinfo.h \
		/home/ctools/qt-5.6-arm/include/QtCore/qlogging.h \
		/home/ctools/qt-5.6-arm/include/QtCore/qflags.h \
		/home/ctools/qt-5.6-arm/include/QtCore/qatomic.h \
		/home/ctools/qt-5.6-arm/include/QtCore/qbasicatomic.h \
		/home/ctools/qt-5.6-arm/include/QtCore/qatomic_bootstrap.h \
		/home/ctools/qt-5.6-arm/include/QtCore/qgenericatomic.h \
		/home/ctools/qt-5.6-arm/include/QtCore/qatomic_cxx11.h \
		/home/ctools/qt-5.6-arm/include/QtCore/qatomic_gcc.h \
		/home/ctools/qt-5.6-arm/include/QtCore/qatomic_msvc.h \
		/home/ctools/qt-5.6-arm/include/QtCore/qatomic_armv7.h \
		/home/ctools/qt-5.6-arm/include/QtCore/qatomic_armv6.h \
		/home/ctools/qt-5.6-arm/include/QtCore/qatomic_armv5.h \
		/home/ctools/qt-5.6-arm/include/QtCore/qatomic_ia64.h \
		/home/ctools/qt-5.6-arm/include/QtCore/qatomic_x86.h \
		/home/ctools/qt-5.6-arm/include/QtCore/qatomic_unix.h \
		/home/ctools/qt-5.6-arm/include/QtCore/qglobalstatic.h \
		/home/ctools/qt-5.6-arm/include/QtCore/qmutex.h \
		/home/ctools/qt-5.6-arm/include/QtCore/qnumeric.h \
		/home/ctools/qt-5.6-arm/include/QtCore/qversiontagging.h \
		/home/ctools/qt-5.6-arm/include/QtCore/qobjectdefs.h \
		/home/ctools/qt-5.6-arm/include/QtCore/qnamespace.h \
		/home/ctools/qt-5.6-arm/include/QtCore/qobjectdefs_impl.h \
		/home/ctools/qt-5.6-arm/include/QtGui/qwindowdefs_win.h \
		/home/ctools/qt-5.6-arm/include/QtCore/qobject.h \
		/home/ctools/qt-5.6-arm/include/QtCore/qstring.h \
		/home/ctools/qt-5.6-arm/include/QtCore/qchar.h \
		/home/ctools/qt-5.6-arm/include/QtCore/qbytearray.h \
		/home/ctools/qt-5.6-arm/include/QtCore/qrefcount.h \
		/home/ctools/qt-5.6-arm/include/QtCore/qarraydata.h \
		/home/ctools/qt-5.6-arm/include/QtCore/qstringbuilder.h \
		/home/ctools/qt-5.6-arm/include/QtCore/qlist.h \
		/home/ctools/qt-5.6-arm/include/QtCore/qalgorithms.h \
		/home/ctools/qt-5.6-arm/include/QtCore/qiterator.h \
		/home/ctools/qt-5.6-arm/include/QtCore/qhashfunctions.h \
		/home/ctools/qt-5.6-arm/include/QtCore/qpair.h \
		/home/ctools/qt-5.6-arm/include/QtCore/qbytearraylist.h \
		/home/ctools/qt-5.6-arm/include/QtCore/qstringlist.h \
		/home/ctools/qt-5.6-arm/include/QtCore/qregexp.h \
		/home/ctools/qt-5.6-arm/include/QtCore/qstringmatcher.h \
		/home/ctools/qt-5.6-arm/include/QtCore/qcoreevent.h \
		/home/ctools/qt-5.6-arm/include/QtCore/qscopedpointer.h \
		/home/ctools/qt-5.6-arm/include/QtCore/qmetatype.h \
		/home/ctools/qt-5.6-arm/include/QtCore/qvarlengtharray.h \
		/home/ctools/qt-5.6-arm/include/QtCore/qcontainerfwd.h \
		/home/ctools/qt-5.6-arm/include/QtCore/qobject_impl.h \
		/home/ctools/qt-5.6-arm/include/QtCore/qmargins.h \
		/home/ctools/qt-5.6-arm/include/QtGui/qpaintdevice.h \
		/home/ctools/qt-5.6-arm/include/QtCore/qrect.h \
		/home/ctools/qt-5.6-arm/include/QtCore/qsize.h \
		/home/ctools/qt-5.6-arm/include/QtCore/qpoint.h \
		/home/ctools/qt-5.6-arm/include/QtGui/qpalette.h \
		/home/ctools/qt-5.6-arm/include/QtGui/qcolor.h \
		/home/ctools/qt-5.6-arm/include/QtGui/qrgb.h \
		/home/ctools/qt-5.6-arm/include/QtGui/qrgba64.h \
		/home/ctools/qt-5.6-arm/include/QtGui/qbrush.h \
		/home/ctools/qt-5.6-arm/include/QtCore/qvector.h \
		/home/ctools/qt-5.6-arm/include/QtGui/qmatrix.h \
		/home/ctools/qt-5.6-arm/include/QtGui/qpolygon.h \
		/home/ctools/qt-5.6-arm/include/QtGui/qregion.h \
		/home/ctools/qt-5.6-arm/include/QtCore/qdatastream.h \
		/home/ctools/qt-5.6-arm/include/QtCore/qiodevice.h \
		/home/ctools/qt-5.6-arm/include/QtCore/qline.h \
		/home/ctools/qt-5.6-arm/include/QtGui/qtransform.h \
		/home/ctools/qt-5.6-arm/include/QtGui/qpainterpath.h \
		/home/ctools/qt-5.6-arm/include/QtGui/qimage.h \
		/home/ctools/qt-5.6-arm/include/QtGui/qpixelformat.h \
		/home/ctools/qt-5.6-arm/include/QtGui/qpixmap.h \
		/home/ctools/qt-5.6-arm/include/QtCore/qsharedpointer.h \
		/home/ctools/qt-5.6-arm/include/QtCore/qshareddata.h \
		/home/ctools/qt-5.6-arm/include/QtCore/qhash.h \
		/home/ctools/qt-5.6-arm/include/QtCore/qsharedpointer_impl.h \
		/home/ctools/qt-5.6-arm/include/QtGui/qfont.h \
		/home/ctools/qt-5.6-arm/include/QtGui/qfontmetrics.h \
		/home/ctools/qt-5.6-arm/include/QtGui/qfontinfo.h \
		/home/ctools/qt-5.6-arm/include/QtWidgets/qsizepolicy.h \
		/home/ctools/qt-5.6-arm/include/QtGui/qcursor.h \
		/home/ctools/qt-5.6-arm/include/QtGui/qkeysequence.h \
		/home/ctools/qt-5.6-arm/include/QtGui/qevent.h \
		/home/ctools/qt-5.6-arm/include/QtCore/qvariant.h \
		/home/ctools/qt-5.6-arm/include/QtCore/qmap.h \
		/home/ctools/qt-5.6-arm/include/QtCore/qdebug.h \
		/home/ctools/qt-5.6-arm/include/QtCore/qtextstream.h \
		/home/ctools/qt-5.6-arm/include/QtCore/qlocale.h \
		/home/ctools/qt-5.6-arm/include/QtCore/qset.h \
		/home/ctools/qt-5.6-arm/include/QtCore/qcontiguouscache.h \
		/home/ctools/qt-5.6-arm/include/QtCore/qurl.h \
		/home/ctools/qt-5.6-arm/include/QtCore/qurlquery.h \
		/home/ctools/qt-5.6-arm/include/QtCore/qfile.h \
		/home/ctools/qt-5.6-arm/include/QtCore/qfiledevice.h \
		/home/ctools/qt-5.6-arm/include/QtGui/qvector2d.h \
		/home/ctools/qt-5.6-arm/include/QtGui/qtouchdevice.h \
		/home/ctools/qt-5.6-arm/include/QtWidgets/qtabwidget.h \
		/home/ctools/qt-5.6-arm/include/QtGui/qicon.h \
		ui_testsqlite.h \
		/home/ctools/qt-5.6-arm/include/QtSql/QSqlQuery \
		/home/ctools/qt-5.6-arm/include/QtSql/qsqlquery.h \
		/home/ctools/qt-5.6-arm/include/QtSql/qsql.h \
		/home/ctools/qt-5.6-arm/include/QtSql/qsqldatabase.h \
		/home/ctools/qt-5.6-arm/include/QtSql/QSqlError \
		/home/ctools/qt-5.6-arm/include/QtSql/qsqlerror.h \
		/home/ctools/qt-5.6-arm/include/QtSql/QSqlQueryModel \
		/home/ctools/qt-5.6-arm/include/QtSql/qsqlquerymodel.h \
		/home/ctools/qt-5.6-arm/include/QtCore/qabstractitemmodel.h \
		/home/ctools/qt-5.6-arm/include/QtCore/QDebug
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o testsqlite.o testsqlite.cpp

moc_testsqlite.o: moc_testsqlite.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_testsqlite.o moc_testsqlite.cpp

####### Install

install:  FORCE

uninstall:  FORCE

FORCE:

