######################################################################
# Automatically generated by qmake (3.0) ?? 1? 16 13:56:01 2017
######################################################################

QT +=widgets sql
TEMPLATE = app
TARGET = testsqlite
INCLUDEPATH += .

# Input
HEADERS += testsqlite.h
FORMS += testsqlite.ui
SOURCES += main.cpp testsqlite.cpp
